# imagem basica 'Debian Stretch'
FROM debian:stretch

# configura repositorios e troca locale para 'pt_BR.UTF-8'
RUN echo 'deb http://sft.if.usp.br/debian/ stretch main' > /etc/apt/sources.list \
    && echo 'deb-src http://sft.if.usp.br/debian/ stretch main' >> /etc/apt/sources.list \
    && echo 'deb http://sft.if.usp.br/debian/ stretch-updates main' >> /etc/apt/sources.list \
    && echo 'deb-src http://sft.if.usp.br/debian/ stretch-updates main' >> /etc/apt/sources.list \
    && echo 'deb http://sft.if.usp.br/debian-security/ stretch/updates main' >> /etc/apt/sources.list \
    && echo 'deb-src http://sft.if.usp.br/debian-security/ stretch/updates main' >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends locales \
    && localedef -i pt_BR -c -f UTF-8 -A /usr/share/locale/locale.alias pt_BR.UTF-8
ENV LANG pt_BR.UTF-8

# adiciona os pacotes necessarios para testes basicos com ipython2
RUN apt-get install -y \
	bash-completion vim-nox vim-doc git git-doc git-buildpackage \
	make gcc g++ gdb build-essential fakeroot \
	python2.7 python2.7-dev python2.7-doc python2.7-examples \
	python2.7-minimal python2.7-dbg \
	python-pip python-setuptools \
	python-ipython python-ipython-doc python-ipython-genutils \
	python-flask.*$
    && apt-get clean \
    && apt-get install -f

# configura o ambiente
ENV HOME /root
ENV SHELL /bin/bash
USER root
WORKDIR /root

# executa o shell
CMD /bin/bash

# executa o ipython2
#CMD ipython2
